### ISSUE TITLE
Switch exposed incorrectly

### ISSUE THREAD

**Issue by andrey-yantsen** [koying/mqtt_discoverystream_ha#3]
I tried exposing my SwitchBot button-pusher using this integration, and I got the following config:

```json
{"unique_id": "mqtt_switch.ventilation_boost", "name": "Ventilation Boost", "state_topic": "homeassistant/switch/ventilation_boost/state", "json_attributes_topic": "homeassistant/switch/ventilation_boost/attributes", "availability_topic": "homeassistant/switch/ventilation_boost/availability", "device_class": "switch", "payload_off": "off", "payload_on": "on", "command_topic": "homeassistant/switch/ventilation_boost/set", "device": {"manufacturer": "switchbot", "model": "WoHand", "name": "Ventilation boost", "connections": [["mac", "d5:b9:b6:b8:a2:1c"]]}, "platform": "mqtt"}
```

Key `device_class` is not allowed in the switches, unfortunately.

**Comment by koying** [comment]
It's quite unclear whether switches support device_class or not. I'll open an HA issue to have clarification.

Anyway, mqtt_discovery only publishes the attributes an entity has:
- Or device_class is not supported for switches, and it should be removed from switchbot
- Or it is, and support should be added to the core MQTT discovery

**Comment by andrey-yantsen** [comment]
Ha! Yeah, I thought that it’s not that easy :)

Thanks!

**Comment by andrey-yantsen** [comment]
Thanks! I’ve added a temporary hack to the integration locally, so I’m happy to wait :)
