### ISSUE TITLE
What is the intended purpose

### ISSUE THREAD

**Issue by sylvaindc** [koying/mqtt_discoverystream_ha#4]
Hi, 

This project sounds very cool and it may solve an issue I have (mqtt devices that do not send an auto discover message). I dont fully understand the problem the project is solving. Could you elaborate on that a bit?

**Comment by koying** [comment]
The problem it's solving is that there is no automatic way to create MQTT discovery entries from inside HA

**Comment by sylvaindc** [comment]
That does sound like what I tried to do :) I'll give it a try, thanks!

**Comment by MYG63** [comment]
You may duplicate all states from one HA to another HA using MQTT. I use that for development on the second HA where you cannot "destroy" anything inside the first HA on side 1.
It works great

**Comment by gon0** [comment]
Hello everyone, 
thank you for clarifying. I am trying to get started with this, but i did not find an example somewhere. Or the usage is just too easy and I am thinking too complicated, maybe ;)

I created MQTT discovery messages, that work well when being sent to the MQTT broker. e.g.:
topic: "homeassistant/sensor/BlumiSolar2/temperature/config"
payload:
```
{
  "name": "BlumiSolar2 Temperature",
  "unique_id": "BlumiSolar2_temperature",
  "state_topic": "ESP32_SOLAR2_Pflanzen/chg_temp2",
  "device_class": "temperature",
  "unit_of_measurement": "°C",
  "icon": "mdi:thermometer",
  "expire_after": 660,
  "device": {
    "identifiers": [
      "BlumiSolar2"
    ],
	"model": "BlumiSolar",
    "name": "BlumiSolar2",
    "sw_version": "v1.0.0",
    "hw_version": "v1.0",
    "manufacturer": "gon0"
	}
}
```
I need this (and many other) discovery payloads sent regularly, so the sensor data published at "ESP32_SOLAR2_Pflanzen/chg_temp2" is shown in HA.

So how do I proceed? Do I need to put my payloads and topics somewhere into a file?

Have a great day :)

**Comment by koying** [comment]
The discovery payloads *do not* need to be sent repeatedly, just once in "retain".
See https://www.home-assistant.io/integrations/mqtt#mqtt-discovery for the documentation
