### ISSUE TITLE
Errors with 2022.11.x

### ISSUE THREAD

**Issue by RogerSelwyn** [koying/mqtt_discoverystream_ha#8]
Since upgrading to 2022.11 I'm finding the MQTT Discovery Stream is irregularly not getting setup during reboot. I think this is a race condition with MQTT integration (which I can see you have a dependency on).

The problem seems to be the subscriptions at the end of your code, which I believe handle switch turn on/off events (which I don't use). I think they are subscribing before MQTT is setup. The I debug back into core code to this, it is the Matt_data which is empty, `mqtt_config_entry_enabled(hass)` returns true:

```
    Call the return value to unsubscribe.
    """
    mqtt_data = get_mqtt_data(hass, True)
    if mqtt_data.client is None or not mqtt_config_entry_enabled(hass):
        raise HomeAssistantError(
            f"Cannot subscribe to topic '{topic}', MQTT is not enabled"
        )
```

For Platforms you can tell the setup routine that the Platform entry/ConfigEntry isn't ready and then the setup will try again in 60 seconds, but I can't see how to do this with your integration. It's probably a case of adding a future task to retry again in 60 seconds.

The code lines don't line up with your GitHub since you added some extra code since v0.9:

```
2022-11-05 09:03:14.224 ERROR (MainThread) [homeassistant.setup] Error during setup of component mqtt_discoverystream
Traceback (most recent call last):
  File "/workspaces/core/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/home/Hassio/dev-config/custom_components/mqtt_discoverystream/__init__.py", line 302, in async_setup
    await hass.components.mqtt.async_subscribe(f"{base_topic}switch/+/set", message_received)
  File "/workspaces/core/homeassistant/components/mqtt/client.py", line 196, in async_subscribe
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Cannot subscribe to topic 'debiandev/switch/+/set', MQTT is not enabled
```

**Comment by RogerSelwyn** [comment]
In the interim I have done this in my installs

`from homeassistant.exceptions import HomeAssistantError`

```
    if publish_discovery:
        try:
            await hass.components.mqtt.async_subscribe(
                f"{base_topic}switch/+/set", message_received
            )
            await hass.components.mqtt.async_subscribe(
                f"{base_topic}light/+/set_light", message_received
            )
        except HomeAssistantError:
            _LOGGER.warning("MQTT Not ready")
```

**Comment by Vedeneb** [comment]
Hi,
I have the same issue. The integration won't setup at all anymore, even after several restarts.
Where have you made these changes? Is this just a workaround which ignores if subscribing fails (because you don't use the on/off events)?
Thanks.

**Comment by RogerSelwyn** [comment]
> Hi,
> I have the same issue. The integration won't setup at all anymore, even after several restarts.
> Where have you made these changes? Is this just a workaround which ignores if subscribing fails (because you don't use the on/off events)?
> Thanks.

Yes, in `__init__.py`

**Comment by koying** [comment]
I haven't updated yet, but this seems ok on a test instance

```diff
diff --git a/custom_components/mqtt_discoverystream/__init__.py b/custom_components/mqtt_discoverystream/__init__.py
index ff5ab3f..93b06ff 100644
--- a/custom_components/mqtt_discoverystream/__init__.py
+++ b/custom_components/mqtt_discoverystream/__init__.py
@@ -39,6 +39,7 @@ from homeassistant.helpers.entityfilter import (
 )
 from homeassistant.helpers.event import async_track_state_change
 from homeassistant.helpers.json import JSONEncoder
+from homeassistant.setup import async_when_setup
 
 _LOGGER = logging.getLogger(__name__)
 
@@ -305,10 +306,13 @@ async def async_setup(hass, config):
             await mqtt_publish(f"{mybase}state", payload, 1, True)
 
 
-    if publish_discovery:
+    async def async_subscribe_mqtt():
         await hass.components.mqtt.async_subscribe(f"{base_topic}switch/+/set", message_received)
         await hass.components.mqtt.async_subscribe(f"{base_topic}light/+/set_light", message_received)
 
+    if publish_discovery:
+        async_when_setup(hass, "mqtt", async_subscribe_mqtt)
+
     async_track_state_change(hass, MATCH_ALL, _state_publisher)
     return True
```

**Comment by RogerSelwyn** [comment]
> I haven't updated yet, but this seems ok on a test instance
> 
> ```diff
> diff --git a/custom_components/mqtt_discoverystream/__init__.py b/custom_components/mqtt_discoverystream/__init__.py
> index ff5ab3f..93b06ff 100644
> --- a/custom_components/mqtt_discoverystream/__init__.py
> +++ b/custom_components/mqtt_discoverystream/__init__.py
> @@ -39,6 +39,7 @@ from homeassistant.helpers.entityfilter import (
>  )
>  from homeassistant.helpers.event import async_track_state_change
>  from homeassistant.helpers.json import JSONEncoder
> +from homeassistant.setup import async_when_setup
>  
>  _LOGGER = logging.getLogger(__name__)
>  
> @@ -305,10 +306,13 @@ async def async_setup(hass, config):
>              await mqtt_publish(f"{mybase}state", payload, 1, True)
>  
>  
> -    if publish_discovery:
> +    async def async_subscribe_mqtt():
>          await hass.components.mqtt.async_subscribe(f"{base_topic}switch/+/set", message_received)
>          await hass.components.mqtt.async_subscribe(f"{base_topic}light/+/set_light", message_received)
>  
> +    if publish_discovery:
> +        async_when_setup(hass, "mqtt", async_subscribe_mqtt)
> +
>      async_track_state_change(hass, MATCH_ALL, _state_publisher)
>      return True
> ```

Sorry, only just seen your response on this. I tried implementing into a fork of your code. I still get the same problem unfortunately. I'm guessing MQTT is declaring it is setup before it is. I'm considering putting a retry in for 10 seconds or so, when I figure out the re-queuing mechanism (just got to look it up).

By the way, I have added climate to your code. On the way I've done a substantial re-org of your code because I found it confusing as a continuous stream, so I've broken out the Discovery element which brings the basis state stream pretty much back to the basic core code, with a couple of hooks. I'm happy to submit it back to you if you are interested.

**Comment by RogerSelwyn** [comment]
May just try this - https://developers.home-assistant.io/docs/integration_setup_failures/#handling-offline-or-unavailable-devices-and-services

Then core will retry again, I think in 30 seconds.

**Comment by RogerSelwyn** [comment]
> May just try this - https://developers.home-assistant.io/docs/integration_setup_failures/#handling-offline-or-unavailable-devices-and-services
> 
> Then core will retry again, I think in 30 seconds.

That doesn't work

**Comment by dingausmwald** [comment]
I am quite interested in the climate part. Should i install the fork of @RogerSelwyn or will this be implemented in the near future @koying?

**Comment by dingausmwald** [comment]
Just tried your fork and for climate it only works one way. I get

`Template variable warning: 'dict object' has no attribute 'hvac_action' when rendering '{{ value_json.hvac_action }}'`

in the logs.
